language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn
script:
  - yarn lint
  - yarn build --production
  - yarn test -- --runInBand
after_success:
  - yarn semantic-release
branches:
  only:
    - master
