language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
  - '6'
dist: precise
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn
script:
  - yarn lint
  - yarn build --production
  - yarn test -- --runInBand
after_success:
  - yarn travis-deploy-once "yarn add semantic-release@^15.9.8 && yarn semantic-release"
branches:
  only:
    - master
